version: "3.9"
services:
  backend:
    build: .
    ports:
      - "9090:9090"  
    env_file:
      - .env  
    depends_on:
      - db  
    volumes:
      - .:/usr/src/app  
    command: >
      sh -c "npx prisma migrate deploy && npm start"

  db:
    image: mysql:8.0 
    container_name: prisma_mysql
    restart: always
    ports:
      - "3308:3308"
    env_file:
      - .env  
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data: 
